create database STAGING_NR;
create database PROD_NR;

ALTER database STAGING_NR set data_retention_time_in_days = 5;
ALTER database PROD_NR set data_retention_time_in_days = 5;
--i have added the retension its not in the requirement.

show databases;

create schema STAGING_NR.RAW 
DATA_RETENTION_TIME_IN_DAYS = 3;

create schema STAGING_NR.CLEAN 
DATA_RETENTION_TIME_IN_DAYS = 3;

create schema PROD_NR.REPORTING 
DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE WAREHOUSE IMPORT_WH_NR 
WITH WAREHOUSE_SIZE = 'MEDIUM'
WAREHOUSE_TYPE = 'STANDARD'
INITIALLY_SUSPENDED = TRUE
AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE 
--MIN_CLUSTER_COUNT = 1 
--MAX_CLUSTER_COUNT = 1 
SCALING_POLICY = 'STANDARD'
COMMENT = 'Import warehouse to hold the staging data';

CREATE WAREHOUSE TRANSFORM_WH_NR 
WITH WAREHOUSE_SIZE = 'MEDIUM'
WAREHOUSE_TYPE = 'STANDARD'
INITIALLY_SUSPENDED = TRUE
AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE 
--MIN_CLUSTER_COUNT = 1 
--MAX_CLUSTER_COUNT = 1 
SCALING_POLICY = 'STANDARD'
COMMENT = 'Holds the transformed data of staging data';

CREATE WAREHOUSE REPORTING_WH_NR 
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
INITIALLY_SUSPENDED = TRUE
AUTO_SUSPEND = 900 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 5 
SCALING_POLICY = 'STANDARD'
COMMENT = 'Reporting warehouse will have the data to generate dashboards';

show warehouses;

CREATE ROLE IMPORT_ROLE_NR;
CREATE ROLE TRANSFORM_ROLE_NR;
CREATE ROLE REPORTING_ROLE_NR;

CREATE USER UserImport PASSWORD = 'abc123' MUST_CHANGE_PASSWORD = FALSE DEFAULT_ROLE = IMPORT_ROLE_NR DEFAULT_WAREHOUSE = IMPORT_WH_NR;
CREATE USER UserTransform PASSWORD = 'xyz321' MUST_CHANGE_PASSWORD = FALSE DEFAULT_ROLE = TRANSFORM_ROLE_NR DEFAULT_WAREHOUSE = TRANSFORM_WH_NR;
CREATE USER UserReporting PASSWORD = 'zaq135' MUST_CHANGE_PASSWORD = FALSE DEFAULT_ROLE = REPORTING_ROLE_NR DEFAULT_WAREHOUSE = REPORTING_WH_NR;


GRANT ROLE IMPORT_ROLE_NR TO USER UserImport;
GRANT ROLE TRANSFORM_ROLE_NR TO USER UserImport;
GRANT ROLE REPORTING_ROLE_NR TO USER UserImport;


GRANT USAGE ON WAREHOUSE IMPORT_WH_NR TO ROLE IMPORT_ROLE_NR;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH_NR TO ROLE TRANSFORM_ROLE_NR;
GRANT USAGE ON WAREHOUSE REPORTING_WH_NR TO ROLE REPORTING_ROLE_NR;

GRANT USAGE ON DATABASE STAGING_NR TO ROLE IMPORT_ROLE_NR;
GRANT USAGE ON SCHEMA STAGING_NR.RAW TO ROLE IMPORT_ROLE_NR;
GRANT USAGE ON SCHEMA STAGING_NR.CLEAN TO ROLE IMPORT_ROLE_NR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING_NR.RAW TO ROLE IMPORT_ROLE_NR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING_NR.CLEAN TO ROLE IMPORT_ROLE_NR;

GRANT USAGE ON DATABASE STAGING_NR TO ROLE TRANSFORM_ROLE_NR;
GRANT USAGE ON SCHEMA STAGING_NR.CLEAN TO ROLE TRANSFORM_ROLE_NR;
GRANT USAGE ON DATABASE PROD_NR TO ROLE TRANSFORM_ROLE_NR;
GRANT USAGE ON SCHEMA PROD_NR.REPORTING TO ROLE TRANSFORM_ROLE_NR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING_NR.CLEAN TO ROLE TRANSFORM_ROLE_NR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PROD_NR.REPORTING TO ROLE TRANSFORM_ROLE_NR;

GRANT USAGE ON DATABASE PROD_NR TO ROLE REPORTING_ROLE_NR;
GRANT USAGE ON SCHEMA PROD_NR.REPORTING TO ROLE REPORTING_ROLE_NR;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_NR.REPORTING TO ROLE REPORTING_ROLE_NR;

CREATE RESOURCE MONITOR IMPORT_MONITOR_NR WITH CREDIT_QUOTA = 100;
CREATE RESOURCE MONITOR TRANSFORM_MONITOR_NR WITH CREDIT_QUOTA = 100;
CREATE RESOURCE MONITOR REPORTING_MONITOR_NR WITH CREDIT_QUOTA = 100;

ALTER WAREHOUSE IMPORT_WH_NR SET RESOURCE_MONITOR = IMPORT_MONITOR_NR;
ALTER WAREHOUSE TRANSFORM_WH_NR SET RESOURCE_MONITOR = TRANSFORM_MONITOR_NR;
ALTER WAREHOUSE REPORTING_WH_NR SET RESOURCE_MONITOR = REPORTING_MONITOR_NR;






